[package]
name = "rimcli"
description = "Unified CLI for rim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "rim"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
colored = "3.1.1"
indicatif = "0.18.3"
rimfs = { workspace = true, features = ["std", "fat", "exfat", "ext", "ntfs"] }
rimgen = { workspace = true, features = ["std", "fat", "exfat", "ext", "ntfs"] }
rimhost.workspace = true
rimimg = { workspace = true, features = ["std"] }
rimio = { workspace = true, features = ["std"] }
rimpart = { workspace = true, features = ["std"] }
tempfile = "3.20.0"

[lints]
workspace = true
