[workspace]
resolver = "3"

members = [
    "rimcli",
    "rimgen",
    "rimimg",
    "rimhost",
    "rimfs-core",
    "rimfs-fat",
    "rimfs-exfat",
    "rimfs-ext",
    "rimfs-ntfs",
    "rimfs",
    "rimpart",
    "rimio",
    "sector-analyzer",
]

default-members = ["rimcli", "rimgen", "rimimg", "rimhost", "rimfs-core", "rimfs-fat", "rimfs-exfat", "rimfs-ext", "rimfs-ntfs", "rimfs", "rimpart", "rimio"]

[workspace.package]
version = "0.6.2"
edition = "2024"
license = "MIT"
authors = ["Killian Massa (Mki) <contact@mki.dev>"]
repository = "https://github.com/mkidv/rim"
homepage = "https://github.com/mkidv/rim"
keywords = ["fat", "exfat", "ext", "ntfs", "mbr", "gpt", "disk-image"]
categories = ["filesystem", "embedded", "no-std", "development-tools"]

[workspace.dependencies]
rimcli = { path = "rimcli", version = "0.6.2" }
rimfs = { path = "rimfs", version = "0.6.2" }
rimfs-core = { path = "rimfs-core", version = "0.6.2" }
rimfs-fat = { path = "rimfs-fat", version = "0.6.2" }
rimfs-exfat = { path = "rimfs-exfat", version = "0.6.2" }
rimfs-ext = { path = "rimfs-ext", version = "0.6.2" }
rimfs-ntfs = { path = "rimfs-ntfs", version = "0.6.2" }
rimgen = { path = "rimgen", version = "0.6.2" }
rimhost = { path = "rimhost", version = "0.6.2" }
rimimg = { path = "rimimg", version = "0.6.2" }
rimio = { path = "rimio", version = "0.6.2" }
rimpart = { path = "rimpart", version = "0.6.2" }

[workspace.lints.clippy]
chunks_exact_to_as_chunks = "allow"

