[package]
name = "wasm-synth"
description = "WASM disk synthesis example for rim"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rimio = { version = "0.8.2", path = "../../rimio", default-features = false, features = ["alloc"] }
rimpart = { version = "0.8.2", path = "../../rimpart", default-features = false, features = ["alloc"] }
rimfs = { version = "0.8.2", path = "../../rimfs", default-features = false, features = ["alloc", "fat", "ext", "exfat", "ntfs", "tar"] }
rimgen = { version = "0.8.2", path = "../../rimgen", default-features = false, features = ["alloc", "fat", "ext", "exfat", "ntfs"] }
rimimg = { version = "0.8.2", path = "../../rimimg", default-features = false, features = ["alloc"] }
dlmalloc = { version = "0.2", default-features = false, features = ["global"] }

[features]
default = []
host = []

[[bin]]
name = "build_alpine_host"
path = "src/bin/build_alpine_host.rs"
required-features = ["host"]

[dev-dependencies]
rimfs-fat = { version = "0.8.2", path = "../../rimfs-fat", default-features = false, features = ["alloc"] }
rimfs-ext = { version = "0.8.2", path = "../../rimfs-ext", default-features = false, features = ["alloc"] }
