[package]
name = "rimio"
description = "I/O abstraction for rim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["std", "mmap"]
alloc = ["zerocopy/alloc"]
mem   = []
std   = ["alloc"]
mmap  = ["dep:memmap2", "std"]
uefi  = ["dep:uefi"]

[dependencies]
paste = "1.0.15"
uefi = { version = "0.40.0", optional = true }
zerocopy = { version = "0.8.25", default-features = false }
memmap2 = { version = "0.9", optional = true }

[dev-dependencies]
tempfile = "3.20"

[lints]
workspace = true

