[package]
name = "uefi-synth"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[[bin]]
name = "uefi-synth"
path = "src/main.rs"
test = false

[dependencies]
uefi = { version = "0.36.1", default-features = false, features = ["alloc"] }
rimio = { path = "../../rimio", default-features = false, features = ["alloc", "uefi"] }
rimpart = { path = "../../rimpart", default-features = false, features = ["alloc"] }
rimfs = { path = "../../rimfs", default-features = false, features = ["alloc", "fat", "ext", "ntfs", "exfat", "tar"] }
rimgen = { path = "../../rimgen", default-features = false, features = ["alloc", "fat", "ext", "ntfs", "exfat"] }
