[package]
name = "uefi-synth"
description = "UEFI BlockIO disk synthesis example for rim"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[features]
default = []
dangerous-uefi-write = []

[[bin]]
name = "uefi-synth"
path = "src/main.rs"
test = false

[dependencies]
uefi = { version = "0.36.1", default-features = false, features = ["alloc"] }
rimio = { version = "0.8.1", path = "../../rimio", default-features = false, features = ["alloc", "uefi"] }
rimpart = { version = "0.8.1", path = "../../rimpart", default-features = false, features = ["alloc"] }
rimfs = { version = "0.8.1", path = "../../rimfs", default-features = false, features = ["alloc", "fat", "ext", "ntfs", "exfat", "tar"] }
rimgen = { version = "0.8.1", path = "../../rimgen", default-features = false, features = ["alloc", "fat", "ext", "ntfs", "exfat"] }
