[package]
name = "sector-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
rimpart = { path = "../rimpart", features = ["std"] }
rimio = { path = "../rimio", features = ["std"] }
rimfs = { path = "../rimfs", features = ["std"] }
zerocopy = { version = "0.8.25", features = ["derive"] }
memchr = "2.7"

[lints]
workspace = true

