[package]
name = "sector-analyzer"
description = "Sector analysis tool for rim"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]
rimpart = { workspace = true, features = ["std"] }
rimio = { workspace = true, features = ["std"] }
rimimg = { workspace = true, features = ["std"] }
rimfs = { workspace = true, features = ["std", "fat", "exfat", "ext", "ntfs", "iso"] }
zerocopy = { version = "0.8.25", features = ["derive"] }
memchr = "2.7"

[lints]
workspace = true
