[package]
name = "rimfs-ntfs"
description = "NTFS filesystem implementation for rimfs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["mem", "std", "alloc"]
mem = ["rimio/mem", "rimfs-core/mem"]
std = ["rimio/std", "alloc", "crc32fast/std", "time/std", "rimfs-core/std"]
uefi = ["rimio/uefi", "alloc", "rimfs-core/uefi"]
alloc = ["rimfs-core/alloc"]

[dependencies]
bitflags = "2.9.1"
crc32fast = { version = "1.4.2", default-features = false }
rimio = { path = "../rimio", version = "0.6.0" }
rimfs-core = { path = "../rimfs-core", version = "0.6.0", default-features = false }
time = { version = "0.3.41", default-features = false }
zerocopy = { version = "0.8.25", default-features = false, features = ["derive"] }

[package.metadata.docs.rs]
features = ["std"]

[lints]
workspace = true

