[package]
name = "rimimg"
description = "Disk image and container formats for rim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["vhd", "vmdk", "qcow2", "disk-image", "no-std"]
categories.workspace = true

[features]
default = ["std"]
alloc = ["rimio/alloc"]
std = [
    "alloc",
    "rimio/std",
    "time/std",
    "uuid/std",
    "uuid/v4",
]

[dependencies]
rimio.workspace = true
time = { version = "0.3.41", default-features = false }
uuid = { version = "1.17", default-features = false }
zerocopy = { version = "0.8.25", default-features = false, features = ["derive"] }

[package.metadata.docs.rs]
features = ["std"]

[lints]
workspace = true

