[package]
name = "rimimg"
description = "Disk image and container formats for rim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow = "1.0"
rimio = { workspace = true, features = ["std"] }
tempfile = "3.20"
time = { version = "0.3.41", default-features = false, features = ["std"] }
uuid = { version = "1.17", features = ["v4"] }
zerocopy = { version = "0.8.25", default-features = false, features = ["derive"] }

[dev-dependencies]
tempfile = "3.20"

[lints]
workspace = true

