[package]
name = "rimhost"
description = "OS-native host storage integrations for rim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow = "1.0.98"
rimgen = { workspace = true, features = ["std"] }
rimimg = { workspace = true, features = ["std"] }
rimio = { workspace = true, features = ["std"] }
tempfile = "3.20.0"
which = "8.0.0"

[lints]
workspace = true
