[package]
name = "rimgen"
description = "Declarative disk image generation engine for rim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "rimgen"
path = "src/lib.rs"

[dependencies]
rimfs.workspace = true
rimimg.workspace = true
rimio.workspace = true
rimpart.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
tempfile = { version = "3.20.0" }
toml = "0.9.7"
uuid = { version = "1.17.0", features = ["v4", "serde"] }

[lints]
workspace = true

